### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by keviny22** [kalinchuk/quickbase#2]
@kalinchuk I have a situation where I need to be able to set the proxy and cannot rely on the http_proxy environment variables.

There is a pattern to do this for users of HTTParty ex. https://github.com/hipchat/hipchat-rb/blob/master/lib/hipchat/client.rb

I coded it up a bit (following the same pattern as hipchat) and wanted to run it by you to see if you would agree with the approach so it could be merged into the main code.

https://github.com/keviny22/quickbase/pull/1

let me know what you think.

Thanks!

**Comment by kalinchuk** [comment]
That repo is not really being maintained so as long as the code looks OK and the tests pass I can merge it in.
