### ISSUE TITLE
The ":fmt" parameter in the "do_query" method doesn't appear to have any effect

### ISSUE THREAD

**Issue by ShaunGrey** [kalinchuk/quickbase#4]
Hi! I was trying to run a query like this, that I believe should return structured data, as described in the [QuickBase API Guide:](http://www.quickbase.com/api-guide/do_query.html)

`contracts = contracts_connection.api.do_query(  :query    =>  "{'13'.CT.'Test'}",`
`:clist    =>  "3.13.8",`
`:friendly =>  "Record ID#.Title.File Name",`
`:fmt      =>  "structured")`

`puts contracts`

However, when I run that, it just returns this:

`{:"Record ID#"=>"1352", :Title=>"Test", :"File Name"=>"Test.pdf"}`

Which is the same result I get when I run the query with the :fmt parameter removed entirely (Specifically, I'm trying to get that "File name" column to return the full URL of the File Attachment value, instead of just the file name). I'm wondering if I'm doing something wrong, or if the problem lies with the Gem.

Thank you for your help, and thank you for making this in the first place!

**Comment by Karlotcha** [comment]
@ShaunGrey Hi Shaun, did you figure out how to use this param? I don't believe the issue lies with the gem but I am not super familiar with the QuickBase API either.

**Comment by ShaunGrey** [comment]
I never did, tragically. I ended up using https://github.com/garethlatwork/quickbase_client which has a lot more functionality. I know it sucks to switch mid-project, but I hightly recommend it!

**Comment by Karlotcha** [comment]
@ShaunGrey no problem, I will close this issue then. Thanks for your participation :slightly_smiling_face:

**Comment by ShaunGrey** [comment]
no problem! thanks for checking in!
