### ISSUE TITLE
QuickBase New Authentication Method (via usertokens)

### ISSUE THREAD

**Issue by pbnj** [kalinchuk/quickbase#7]
QuickBase [announced](http://www.quickbase.com/quickbase-blog/july-2016-release-notes) they will be deprecating the current authentication mechanism (via `apptokens`) in favor of more granular `usertokens`. 

According to their [API Docs](https://help.quickbase.com/api-guide/index.html#create_user_tokens.html), `usertokens` are more flexible as you do not need to send a POST request to `API_Authenticate` to retrieve an `<auth_ticket>`. Instead, once you've generated a `usertoken`, you can simply submit it as part of the params.

PR to follow shortly to support `usertokens`.

**Comment by GiantEnemyCrab** [comment]
Closing this issue as a similar branch has been merged:
https://github.com/kalinchuk/quickbase/pull/9

**Comment by kruzewski** [comment]
Was the apptoken auth method deprecated in the 0.1.0 version? Is the usertoken only working?...btw Quick Base isn't removing the apptoken auth, the usertoken is just an alternative.

**Comment by pbnj** [comment]
From my conversations with QuickBase technical reps, they indicated plans to deprecate apptokens, but no specific timelines.

**Comment by kruzewski** [comment]
Seems odd as having it be user specific is limiting in some cases, i.e. custom js actions.
